name: Build Event

on:
  push:
    branches:
      - event_*

jobs:
  build:
    name: Build Event
    runs-on: [self-hosted, Linux, office]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{secrets.GITHUB_TOKEN}}

      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          clean: true

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies & Build Production
        run: |
          npm install
          npm run build
